# Generated by Django 6.0.1 on 2026-02-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticky_notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
